site_name: Cantor Documentation

# Theme
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'white'
    accent: 'white'
  favicon: 'favicon.ico'
  logo: 'cantor-logo.png'


# Pages
pages:
  - "Introduction": "index.md"
  - "Overview":
    - "Motivation": "motivation.md"
    - "Components": "components.md"
    - "Objects": "objects.md"
    - "Sets": "sets.md"
    - "Maps": "maps.md"
    - "Events": "events.md"
  - "Getting started":
    - "Components": "components.md"
  - "License": "license.md"

# Github repository
repo_name: 'salesforce/cantor'
repo_url: 'https://github.com/salesforce/cantor'

# Copyright
copyright: 'Copyright &copy; 2019 Salesforce'

